apiVersion: v1
kind: Pod
metadata:
  labels:
    app: liveness
  name: liveness-tcp
spec:
  containers:
  - name: liveness
    image: k8s.gcr.io/goproxy:0.1
    ports:
    - containerPort: 8080
    readinessProbe: # comprobación de disponibilidad y desregistra el contenedor si falla (este no reinicia)
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5 # espera 10 segundos antes de la primera comprobación
      periodSeconds: 10 # comprueba cada 5 segundos
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15 # espera 15 segundos antes de la primera comprobación
      periodSeconds: 20 # comprueba cada 20 segundos