apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
---
# creacion de un role para los pods de oscar
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev
  name: cm-role
rules:
- apiGroups: [""] # esto es vacio porque los pods son recursos core k api-resources
  resources: ["configmaps"]
  verbs: ["get", "watch", "list", "patch", "delete"]
---
# creacion de un role bending
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cm-role
  namespace: dev
subjects: # define un usuario, grupo o cuenta de servicio
- kind: User
  name: oscar
  apiGroup: rbac.authorization.k8s.io
roleRef: # referencia al role que se va a asignar
  kind: Role
  name: cm-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: dev
  name: vars
  labels:
    app: front
data:
  db_host: "localhost"
  db_user: "user"