apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: dev
spec:
  hard:
    pods: "3" # Total de pods permitidos en el namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
  namespace: dev
  labels:
    app: front
spec:
  replicas: 4
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: nginx
          image: nginx:alpine