apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
spec:
  containers:
    - name: memory-demo
      image: polinux/stress
      resources:
        requests:
          memory: "1000Gi" #va a tener 100Mi de memoria garantizada
        limits:
          memory: "1000Gi" #va a tener un máximo de 200Mi de memoria
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"] # va a intentar usar 250Mi de memoria el pod no podrá usar más de 200Mi