#con envsubst se utiliza para reemplazar variables de entorno en un archivo YAML.
#envsubst < secure.yml > tmp.yml
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  username: oscar
  password: hola123456
