apiVersion: v1
kind: Secret
metadata:
  name: secret1
type: Opaque
stringData:
  username: admin
  password: "123456789"  # base64 encoded 'password'
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-vol-secret
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: secret1
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret1
              key: password
      volumeMounts:
        - name: secret-vol
          mountPath: /opt
          readOnly: true
  volumes:
    - name: secret-vol
      secret:
        secretName: secret1
        items:
          - key: username
            path: user.txt