apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: nginx
data:
  nginx: |
    server {
        listen 8080;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
          root /usr/share/nginx/html;
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-vars
  labels:
    app: nginx
data:
  db_host: "localhost"
  db_user: "user"
  script: |
    echo "This is a script that runs on startup"
    echo "Database host is $DB_HOST"
    echo "Database user is $DB_USER" > /usr/share/nginx/html/test.html
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: nginx-config-vars
                  key: db_host
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: nginx-config-vars
                  key: db_user
          volumeMounts:
            - name: nginx-vol
              mountPath: /etc/nginx/conf.d/
            - name: script-vol
              mountPath: /opt
      volumes:
        - name: nginx-vol
          configMap:
            name: nginx-config
            items: # esto es del item del configMap (si se quita los items, se monta todo el configMap)
              - key: nginx
                path: default.conf
        - name: script-vol
          configMap:
            name: nginx-config-vars
            items:
              - key: script
                path: script.sh