apiVersion: apps/v1 # Versión de la API de Kubernetes
kind: Deployment # Tipo de recurso que estamos creando
metadata: # Metadatos del recurso
  name: nginx-deployment
spec: # Especificación del recurso (lo que queremos)
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template: # Plantilla para los Pods
    metadata:
      labels:
        app: nginx
    spec: # Especificación del Pod
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80