apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      serviceAccountName: my-service-account
      containers:
        - name: nginx
          image: nginx:alpine
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: service-account-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding-pods
  namespace: default
subjects:
- kind: ServiceAccount # tipo de sujeto
  name: my-service-account # nombre del service account
  apiGroup: "" # apiGroup vacio para core
roleRef: # referencia al role que se va a asignar
  kind: Role
  name: service-account-reader
  apiGroup: rbac.authorization.k8s.io