apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80 # Puerto del Service
      targetPort: 80 # Puerto del contenedor
  type: ClusterIP # Opcional, es el tipo por defecto
