apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
  labels:
    mysql: ready
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce # Solo se puede montar en un nodo a la vez
  hostPath: # hace referencia a un path dentro del nodo donde este corriendo el pod.
    path: /mysql # Ruta en el nodo donde se almacenarán los datos
---
# creacion de un reclamo de volumen persistente PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # Tamaño del volumen solicitado
  selector: # selector para filtrar los PVs disponibles
    matchLabels:
      mysql: ready # solo se seleccionaran los PVs que tengan esta etiqueta
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456789"
          volumeMounts: # Montar el volumen en el contenedor
            - name: mysql-storage
              mountPath: /var/lib/mysql # Ruta dentro del contenedor donde se montará el volumen
      volumes: # Definir el volumen que se va a montar
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: test-pvc # Nombre del PVC que se va a usar