apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: dev
spec:
  hard:
    requests.cpu: "1" # Total de solicitudes de CPU permitidas en el namespace
    requests.memory: "1Gi" # Total de solicitudes de memoria permitidas en el namespace
    limits.cpu: "2" # Límites totales de CPU permitidos en el namespace
    limits.memory:  # Límites totales de memoria permitidos en el namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
  namespace: dev
  labels:
    app: front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          resources:
            requests:
              memory: "500M"
              cpu: "500m" # Solicitud de CPU para el contenedor
            limits: # obligatorio definir los limits
              memory: "500M" # Límite de memoria para el contenedor
              cpu: "500m" # Límite de CPU para el contenedor