apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-k8s-hands-on1
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend-hands-on
        imagePullPolicy: IfNotPresent #si la imagen no existe, la descarga
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-k8s-hands-on1
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 #si el puerto es el mismo, se puede omitir